### ISSUE TITLE
Does the Liferay Boilerplate do Server Side Rendering?

### ISSUE THREAD

**Issue by protoEvangelion** [lundegaard/react-union#101]
_For the Liferay boilerplate example, is it possible to have Server Side Rendering for React components?_

The main use case is related to SEO. For Google's web crawling bots to understand React apps reliably, it has to be **server rendered into HTML**.

I haven't seen anybody do this yet, but I am super eager to see if this is a possibility!

**Comment by wafflepie** [comment]
As a matter of fact, it should be possible! 🙂 

I've already managed to get the critical aspects working, but it's far from complete and the developer experience is lacking (no hot reloading or mocking of portal output). You can have a look at the open PRs (#97, #98). I'm hoping to create a working and usable solution along with proper documentation this fall.

**Comment by protoEvangelion** [comment]
Wow fantastic work!

You are the first person I have seen that has made any significant progress on this.

Let me know if I can help test or provide feedback _(I only know a little bit of Java but understand React pretty well_).

**Comment by tommmyy** [comment]
I think that @wafflepie's answer is great so I am closing this issue.
