### ISSUE TITLE
Boilerplate App started using proxy over locally running Liferay does not find javascript files

### ISSUE THREAD

**Issue by rajdli** [lundegaard/react-union#103]
after deploying **heroPortlet** from **react-union-boilerplate-liferay-basic** to liferay
and started application using the command: yarn **start:proxy**
getting error in console: **Refused to execute script from 'http://localhost:3300/o/liferay-amd-loader/js/vendor.chunk.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.**

The App assumes that the file is on the path: http://localhost:3300/o/liferay-amd-loader/js/vendor.chunk.js'
but it was generated during the build with hash in the name (e.g. vendor.189f0e9c.chunk.js)

- it causes that the **js files are not found** on the path.

Could you please check if it is a bug? Or could you please help?

**Comment by jamescoq** [comment]
Hi rajdli, sorry for the late response.
The mine type is not the issue, the error will disappear once the JS chunks are found. Right now you get the 404 http status in the response right?

try to launch the the app with `yarn start:proxy --release`

we will make updates to react-union-boilerplate-liferay-basic as it is little bit out dated

I will try to make it this ASAP.

**Comment by wafflepie** [comment]
Yeah, the proxy will serve `index.ejs` on the `/` path. We should ignore the directory altogether when running a proxy server.

**Comment by rajdli** [comment]
Thank you very much for help.
Following the steps that you have described:

After run of:
**$ react-union-scripts build --target liferay && yarn liferay-amd SampleApp**
I got this error:
**error An unexpected error occurred: "Command \"liferay-amd\" not found.".**

Please can you help to resolve the issue. Thanks

**Comment by jamescoq** [comment]
Hi, sorry I forgot to describe that script
add "liferay-amd": "node ./tools/amdLoaderScripts.js", to the scripts section in package.json

**Comment by rajdli** [comment]
After making the changes that you have described it is working fine now.
Thank you for help.

**Comment by tommmyy** [comment]
I am closing this. If @rajdli have any other problem we can reopen it.
