### ISSUE TITLE
Rename vendorBlackList to vendorBlacklist

### ISSUE THREAD

**Issue by wafflepie** [lundegaard/react-union#106]
Normally, I wouldn't care, but this is a part of the public API and it should not have mistakes like these (akin to `OccurenceOrderPlugin` instead of `OccurrenceOrderPlugin`).

**Comment by wafflepie** [comment]
Haha, I'm not really sure what to do about this issue. IMO, adding all the dependencies as entry modules is not really viable (we must locate them ourselves instead of relying on another resolution algorithm), so in my `ssr` branch, I decided to leave the logic to webpack's optimization instead and removed the blacklist altogether (albeit not from the defaults, oops). Was there ever a reason for having all the dependencies as entry modules?

Is there even a valid use-case for this blacklist? If so, shouldn't we leave it to the user (who can use `mergeWebpackConfig`)? It might be yet another unnecessary option in our API.

**Comment by tommmyy** [comment]
I am not sure if you should make too many decisions in just one branch. It should be separate PRs.
In a current way (make one PR, rewrite everything, don't ask anybody) it can't be merged.

But I agree that `vendorBlacklist` should be dropped. It is the remnant from first commits.
