### ISSUE TITLE
Consider cleaning up eslint-config-react-union

### ISSUE THREAD

**Issue by wafflepie** [lundegaard/react-union#109]
The boilerplate projects still contain some additional ESLint configuration in their `.eslintrc` files which could instead be moved to the `eslint-config-react-union` package.

In order to reduce maintenance and cognitive overhead, I suggest cleaning up the `eslint-config-react-union` package by removing most of the rules, using a known and popular config such as Airbnb or StandardJS and tweaking only some of the rules specific to React-union or Prettier.

**Comment by tommmyy** [comment]
Thank you for the issue. I agree with the need of updating a few rules (maybe add new). But I strongly disagree with adding another dependency in form of other solutions.

We are a team of experienced developers and we can develop our set of linting rules.

**Comment by wafflepie** [comment]
I don't see how being a team of experienced developers is an argument for developing and maintaining our own set of linting rules. It just creates unnecessary maintenance overhead. It would be much better if we instead focused on more important tasks and if we left the linting rules to someone else (with more resources).

**Comment by aizerin** [comment]
If we adopt someones else linting rules it will bring overhead to learn them, modify them and maintain them with new versions.

**Comment by wafflepie** [comment]
Alright, but I'd like the individual `.eslintrc` files in boilerplates (and real-world projects) to be as clean as possible. Here are some sample rules:

```
module.exports = {
	root: true,
	extends: ['react-union'],
	globals: {
		__DEV__: true,
	},
	rules: {
		'import/no-extraneous-dependencies': [
			'error',
			{
				devDependencies: [
					'packages/**/*.test.js',
					'packages/**/*.stories.js',
					'testsSetup.js',
					'api/**/*',
				],
			},
		],
		// conflicts with prettier
		'react/jsx-max-props-per-line': 0,
		'max-len': 0,
		'space-before-function-paren': [
			'error',
			{
				anonymous: 'never',
				named: 'never',
				asyncArrow: 'always',
			},
		],
	},
};
```

We should definitely make sure that the Prettier integration is as seamless as possible and that they don't conflict (at least use eslint-config-prettier and eslint-plugin-prettier).
