### ISSUE TITLE
Add a "rescan listener"

### ISSUE THREAD

**Issue by wafflepie** [lundegaard/react-union#150]
We should add a new prop to the Union component:
```
<Union listen={scan => window.Liferay.on('startNavigate', scan))}
```
In our Liferay boilerplate, we are using `justRender` instead of rescanning, which... sort of works, but it's not ideal.

Not sure about the name, though. It makes sense from the component perspective (calling `this.props.listen(() => Union.scan(this.props))` in `componentDidMount`). Maybe something like `attachListener` or `addListener`? I think I like `listen` the most.

**Comment by wafflepie** [comment]
Oh, oh, I know! It could be a render prop!

```
<Union>{scan => window.Liferay.on('startNavigate', scan)}</Union>

**Comment by tommmyy** [comment]
@wafflepie I think that `justRender` is proper and explicit way to do it. I am closing it.

**Comment by tommmyy** [comment]
After @lundegaard/union-core discussion we propose the following API:

```js
import { rescan } from 'react-union';


const SomewhereWithinApp = () => {
  // ...
  rescan()
};
```
