### ISSUE TITLE
liferay boilerplate route.getComponent is not a function

### ISSUE THREAD

**Issue by MartinN3** [lundegaard/react-union#234]
This error occurs while deploying either production or dev build of **liferay boilerplate**

**TypeError: route.getComponent is not a function**

at react-union.js:3339

`var loadRouteComponent = function loadRouteComponent(route) {
  return new Promise(function (resolve) {
    return route.getComponent(resolve);
  });
};`

 

Im having  trouble including components into union. Union is on page but no components are included inside, altough portlets are deployed.

**Comment by wafflepie** [comment]
PR merged, I'm closing this as it should be resolved
