### ISSUE TITLE
[react-union-scripts] outputMapper strips slashes from absolute root path

### ISSUE THREAD

**Issue by ArcanisCz** [lundegaard/react-union#31]
When having absolute root path in outputMapper, `outputMapper: {js: '/o/my-theme/js'},` , react-union-scripts will strip leading slash and make that path `/o/my-theme/js`.  modifing **trimSlashes** in utils.js solves the issue. Is there need to strip first slash?

Slash cannot be added post-process to generated html (and script tags), since some chunks are loaded dynamically and needs correct path hardcoded in them (or in chunk doing the loading work)

**Comment by tommmyy** [comment]
Can you please provide your union.config and way to reproduce the bug?
If you have a problem with publicPath, there is property "publicPath".

**Comment by ArcanisCz** [comment]
When based on basic boilerplate, `npm run build` will create folder `build/SampleApp/static/js` where all the scripts are. In index.html, they are referenced as `<script type="text/javascript" src="static/js/vendor.bundle.js">`

My need is to have generated index reference scripts with absolute path and slash at the start, `<script type="text/javascript" src="/static/js/vendor.bundle.js">`

Added union.config.js (version 0.2.1)
```
module.exports = () => ({
    outputMapper: {js: '/static/js'},
});
```
and expected to generate paths with slash at the end. Its due to trimSlashes here (https://github.com/lundegaard/react-union/blob/master/packages/react-union-scripts/scripts/lib/utils.js#L68) removing both slashes, at the end and start. 

When edited that trimSlashes function, it worked as expected in version 0.2.0 . In version 0.2.1, there are errors in console 
```
ERROR: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration[0].output.chunkFilename: A relative path is expected. However the provided value "/static/js/[name].chunk.js" is an absolute path!
 - configuration[0].output.filename: A relative path is expected. However the provided value "/static/js/[name].bundle.js" is an absolute path!

```

My question is, if absolute paths can be enabled since its quite legitimate requirement in some cases? (liferay theme)

**Comment by tommmyy** [comment]
@ArcanisCz I think I can remove it. The trimSlashes is unnecessary validation.
