### ISSUE TITLE
AMD loader module not working on Liferay 7.2.

### ISSUE THREAD

**Issue by jamescoq** [lundegaard/react-union#417]
Since Liferay 7.2 the Liferay.Loader has changed API. The function addModule was dropped without any replacement. 
We need to find a way how to fix this. 
Suggested by liferay:
https://github.com/liferay/liferay-js-toolkit/wiki

link to the liferay issue: https://github.com/liferay/liferay-amd-loader/issues/210

**Comment by tommmyy** [comment]
workin on it

**Comment by tommmyy** [comment]
@jamescoq it should work now in 0.14.0.
