### ISSUE TITLE
add eslint rule "arrow-body-style"

### ISSUE THREAD

**Issue by jamescoq** [lundegaard/react-union#445]
Please add eslint rule:
'arrow-body-style': ['error', 'as-needed'],

The rule will consider this as an error: 
const myFn = () => {
return 5;
}
And would require correction to:
const myFn = () => 5;

**Comment by tommmyy** [comment]
@jamescoq are u available for PR? please add:

```
curly: "error"
```

too.

**Comment by wafflepie** [comment]
for readability, please also consider this rule https://eslint.org/docs/rules/padding-line-between-statements

it might be a pain in the *** to configure, though
