### ISSUE TITLE
[react-union] Naming suggestions

### ISSUE THREAD

**Issue by wafflepie** [lundegaard/react-union#7]
I think that the public API is a really important aspect of a library and the naming should make sense even in the slightest details.

1. I suggest renaming the props of [the Union component](https://github.com/lundegaard/react-union/blob/master/packages/react-union/src/components/Union/Union.js#L15) to `onScanSuccess`, `onScanError` etc. as is common practice in other libraries.

2. I don’t agree with the naming of `justRender` and `justUnmountComponentAtNode` functions, because the word `just` doesn’t make much sense in this context. In my opinion, they should have the same name as the `ReactDOM` functions, as they have the same signature and are intended as a replacement.

3. The name of the union-scripts binary is inconsistent (cf. the package name: react-union-scripts).

4. I absolutely despise the term "DOM-mark", because it simply isn’t a proper English term (wrong translation of the original Czech one). In this case, the original word mark (značka) would translate to tag (which is also incorrect, because it is actually a DOM element). I know that we are used to the term "DOM značka", but for correctness and presentability we should choose a better name. I like the name "DOM element", because it reflects the fact that it can be present anywhere in the document. I also like the name "widget descriptor", because it is precisely the semantic meaning of the element.

You did a really great job with the code base. I will submit issues regarding actual code separately. Can you let me know what you think of these suggestions? I will create PRs for the ones you agree with.

Thanks!

**Comment by tommmyy** [comment]
1) ok
2) I like "just" prefix 
    - no naming conflict with ReactDOM.render 
    - other names like "renderAndCreateNode" is too long for me
    - other suggestions needed
3) yes, must be renamed... in the future we plan to develop "union-scripts" platform and we don't want confuse people, don't we?
4) agree with replacing term dom-mark.. but not with "DOM element".. it can be simply confused with real DOM Element from DOM spec. widget-descriptor is OK

**Comment by wafflepie** [comment]
I agree that `renderAndCreateNode` is way too long, I will try to think of some other names.

I will prepare a PR with the union-scripts binary renamed to `react-union-scripts` as well as another PR where the term DOM mark is replaced in both the documentation and the source code (variable names etc.)

**Comment by tommmyy** [comment]
ok, but `just` methods leave as they are
