### ISSUE TITLE
[react-union] Consider use of react-loadable

### ISSUE THREAD

**Issue by wafflepie** [lundegaard/react-union#9]
Instead of
```
export default {
	path: 'hero',
	getComponents: (cb) => {
		loadWidget((module) => cb(module.default));
	},
};
```
we could do something like
```
import Loadable from 'react-loadable'
import Loading from './Loading'

export default {
	path: 'hero',
	loadable: Loadable({
		loader: () => import('./components/Root'),
		loading: Loading,
	}),
}
```

I find this solution cleaner, because now we needn't create the `.widget.js` files and the user can use their own Loading component easily. It is suggested [here](https://reacttraining.com/react-router/web/guides/code-splitting). What do you think? Can you see any issues with it?

**Comment by tommmyy** [comment]
I think both solutions are compatible... ".widget.js" feature is just out-of-the box functionality that user of react-union-scripts can use. But if he wanna use react-loadable library with import-syntax he surely can.

**Comment by wafflepie** [comment]
It surely is compatible, but you would need to wrap it in another function (which wouldn't be necessary – it would also clean up the code base a little bit, because we wouldn't need to care about loading the components).
